#!/usr/bin/env python3
"""Generate tb/gc9a01_spi_golden.vh from firmware/gc9a01.c (keep in sync)."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
lines = (ROOT / "firmware" / "gc9a01.c").read_text().splitlines()
order = []

# gc9a01_init_regs(): lines before gc9a01_set_full_window
for line in lines:
    if line.strip().startswith("static void gc9a01_set_full_window"):
        break
    m = re.match(r"\s*wr_cmd\(0x([0-9A-Fa-f]+)", line)
    if m:
        order.append((0, int(m.group(1), 16)))
        continue
    m = re.match(r"\s*wr_data\(0x([0-9A-Fa-f]+)", line)
    if m:
        order.append((1, int(m.group(1), 16)))

# gc9a01_set_full_window() body only (not the call site inside fill)
in_win = False
for line in lines:
    if line.strip().startswith("static void gc9a01_set_full_window"):
        in_win = True
        continue
    if in_win:
        if line.strip() == "}":
            break
        m = re.match(r"\s*wr_cmd\(0x([0-9A-Fa-f]+)", line)
        if m:
            order.append((0, int(m.group(1), 16)))
        m = re.match(r"\s*wr_data\(0x([0-9A-Fa-f]+)", line)
        if m:
            order.append((1, int(m.group(1), 16)))

# RAMWR command from gc9a01_fill_screen_rgb565 after set_full_window()
order.append((0, 0x2C))

PREFIX_LEN = len(order)
FILL_BYTES = 240 * 240 * 2
TOTAL = PREFIX_LEN + FILL_BYTES
assert PREFIX_LEN == 193, PREFIX_LEN
assert TOTAL == 115393, TOTAL

outp = Path(__file__).parent / "gc9a01_spi_golden.vh"
with outp.open("w") as out:
    out.write("// Generated by tb/gen_spi_golden.py - do not edit by hand\n")
    out.write(f"localparam integer GC9A01_SPI_PREFIX_LEN = {PREFIX_LEN};\n")
    out.write(f"localparam integer GC9A01_SPI_TOTAL_BYTES = {TOTAL};\n")
    out.write("function [8:0] gc9a01_spi_expected;\n")
    out.write("  input integer k;\n")
    out.write("  begin\n")
    out.write("    case (k)\n")
    for idx, (dc, val) in enumerate(order):
        out.write(f"      {idx}: gc9a01_spi_expected = {{1'd{dc}, 8'h{val:02X}}};\n")
    out.write("      default: begin\n")
    out.write(f"        if (k >= {PREFIX_LEN} && k < {TOTAL}) begin\n")
    out.write(f"          if (((k - {PREFIX_LEN}) & 1) == 0)\n")
    out.write("            gc9a01_spi_expected = {1'b1, 8'hFE};\n")
    out.write("          else\n")
    out.write("            gc9a01_spi_expected = {1'b1, 8'h19};\n")
    out.write("        end else\n")
    out.write("          gc9a01_spi_expected = 9'bx;\n")
    out.write("      end\n")
    out.write("    endcase\n")
    out.write("  end\n")
    out.write("endfunction\n")
print(f"Wrote {outp} prefix_len={PREFIX_LEN} total={TOTAL}")
